name: Building and installing libatomic, into a distribution folder

on: push

jobs:
  building:
    # Name the Job
    name: Extracting and building libatomic
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install necessary build tools and compilers
        run: sudo apt update && sudo apt -y install make build-essential gcc git libgmp-dev libmpc-dev libmpfr-dev g++ libc-dev
      - name: Clonning GCC's sources
        run: git clone git://gcc.gnu.org/git/gcc.git && cd gcc && ./configure --prefix=$GITHUB_WORKSPACE/gcc_dist && make -j4
      - name: Getting sources for POSIX Threads
        run: git clone http://git.savannah.gnu.org/cgit/hurd/libpthread.git/
