name: Building and installing libatomic, into a distribution folder

on: push

jobs:
  building:
    # Name the Job
    name: Extracting and building libatomic
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install necessary build tools and compilers
        run: sudo apt update && sudo apt -y install make build-essential gcc libgmp-dev libmpc-dev libmpfr-dev g++ libc-dev zip 
      - name: Search for libatomic
        run: apt search  libatomic libatomic-devel
      - name: Compress headers from /usr/local/include
        run: zip -r include.zip /usr/local/include/*
      - name: Add sources from headers
        run: zip -ur include.zip /usr/include/*
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload-zip
          path: include.zip
