name: Building and installing libatomic, into a distribution folder

on: push

jobs:
  building:
    # Name the Job
    name: Extrackting and building libatomic
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install necessary build tools and compilers
        run: sudo apt update && sudo apt -y install make build-essential gcc git
      - name: Clonning GCC's sources
        run: git clone git://gcc.gnu.org/git/gcc.git && cd gcc && ./configure --prefix=~/gcc_dist && make -j4
